### ISSUE TITLE
Editor Screen Changes

### ISSUE THREAD

**Issue by phmagic** [DroidPlanner/droidplanner#1356]
- [x] #554 Undo Button
- [x] #951 Moving mission items
- [x] #1122 UI Editor add edit
- [x] #1320 Survey calc is wrong

**Comment by ne0fhyk** [comment]
Fixed by pr #1368
