### ISSUE TITLE
Survey Problems

### ISSUE THREAD

**Issue by arthurbenemann** [DroidPlanner/droidplanner#884]
Proposed improvements:
* [x] Add ability to move the polygon points (#620)
* [ ] New path algorithms (#637)
* [ ] Flight direction indicator (#863)
* [ ] Problems with resolution calculation ( https://github.com/DroidPlanner/droidplanner/issues/661)

## Clean up the lines bellow
* storing and automatically loading the camera and survey settings when switching back into planning mode (especially flight altitude and overlaps)

* allow for different altitude steps intervals (especially in low altitudes): 0-10m in 1m steps, 10-50 in 5 m steps, 50-100 m in 10m steps, 100-1000 in 50 m steps

* synchronizing the maps of the planning and flight data screens and show the same extent when switching between them

* implementing CAM_TRIGG_DIST and WPNAV_SPEED using sliders (and report resulting flight time)

* WPNAV_SPEED might also be set automatically according to the survey/camera data if a minimum shooting interval [s] of the camera is provided by the user (or maybe the *.xml file). Additionally, the user should be able to adjust it manually (especially to lower the calculated speed).

* an option to change the "Yaw behavior during mission (WP_YAW_BEHAVIOUR)" would be helpful. For post processing/as well as visual inspection of the image set it would be good if the yaw is set fixed to the "Hatch angle" of the survey grid (i.e. from "Face next waypoint" or "Face along GPS course" to "Never change yaw") once the copter is on its way between WP1 and WP2 (for sure this only makes sense for copters and I am not sure if this is possible at all during a mission),

### Extras:
>In DP1 it was possible to draw a polygon by setting a series of individual polygon points. In DP2 this is not possible. The advantage is that with the DP1 approach you can avoid spurious polygon points and draw a much more precise polygon.
in DP1 it was possible to move the polygon points around at any stage of mission planning and the survey grid was adjusted automatically (after changing the hatch angle for example). This was perfect, because it allowed for some iterative adaption of the survey area/mission length.
in DP1 it was possible to move single waypoints of the survey grid around. I often use this for security reasons. For example I moved the first way point somewhere close to the home location and the last waypoint as well.

**Comment by ThorstenDP** [comment]
Hi phmagic,

have you closed this issue(s) because of cleaning everthing up before moving to the new 3DR repository?
I am asking because quite a few suggestions have not yet been implemented?
For example: 
- the possibility to set yaw fixed to the "Hatch angle" of the survey grid (and to set WP_YAW_BEHAVIOUR to "Never change yaw") 

as well other suggestions dating back to DP1:
https://github.com/DroidPlanner/droidplanner/issues/325
https://github.com/DroidPlanner/droidplanner/issues/637
https://github.com/DroidPlanner/droidplanner/issues/965

Should I open the isseus again after the transition?
Cheers,
Thorsten

**Comment by ThorstenDP** [comment]
@bbasso , @Thalek,
What I mean is specifically for grid surveys:
- face the copter to the next waypoint if the first waypoint is reached (This angle is the hatch angle you define when setting up the survey)
- and then set WP_YAW_BEHAVOR = 0  ("Never change yaw")

There are several advantages:
- Security: you always know the orientation of the copter in case you have to fly manually 
- Easy image analysis: scanning through the images visually it is much intuitive if they all show the same orientation
- Saving battery and time: It should be (at least a little bit) more efficient if any additional movement is avoided. 

see also a discussion with Arthur at: https://github.com/DroidPlanner/droidplanner/pull/1257#issuecomment-62068316

Adjusting WP_NAV_Speed with a sliver would also be a good addition.

Thanks a lot! Looking forward to any update!
Thorsten

PS: I think it makes more sense to set the angle to the hatch angle defined when creating the grid instead of setting the current yaw at WP1 (when facing to WP2) because there might be some drift due to wind or magnetic interference and thus some offset to the "desired" hatch angle. 

Maybe the easiest would be:
- take off
- go to WP1
- set WP_YAW_BEHAVOR = 0
- set new yaw 
- set CAM_TRIGG_DIST > 0
- proceed mission
- RTL

**Comment by ThorstenDP** [comment]
@bbasso 
if I should explain it in more detail please let me know. I am not a native speaker so my explanations are sometimes a little clumsy...

**Comment by bbasso** [comment]
@ThorstenDP - you're explanation is perfect!

So what you're describing ("face the copter to the next waypoint if the first waypoint is reached (This angle is the hatch angle you define when setting up the survey") is accomplished by WP_YAW_BEHAVOR = 2.  You suggestion of manually setting yaw then going to WP_YAW_BEHAVOR = 0 *may* (havent tested it) not actually update the heading as the yaw drifts, which would be pretty bad.

On a bigger picture leve, maybe you can go into further detail on the problem you are trying to solve....Your 'advantages' listed above (always know copter orientation, all images in same orientation etc.) are all accomplished with the current default survey method.

**Comment by ThorstenDP** [comment]
@bbasso ,
I missed your reply, sorry! 
Can you explain what you mean that yaw drifts? I never had a problem with WP_YAW_BEHAVIOR = 0. There is only some small changes in yaw other the flight. But maybe you are referring to something else?
Let me try to describe in some more detail: 
My main concern in security. Knowing the orientation is especially important when the mission covers a larger area and you operate at the limits of line of sight. If the copter is 300+ m away it is very hard to see if it turns and how fast it is. Keeping track of the copter is crucial. If you become distracted for just a second it is sometimes hard to find it again. It also strongly depends on your position relative to the survey grid, as well as the distance between you and the copter. This is for sure no problem for small area missions, but it is for any grid larger than 250*250m. If yaw is fixed you always know the orientation of the copter. This is why I never change it. It might be a life saver is some cases. 
Would be great if you could give it a try.
